### ISSUE TITLE
envoy-v1.23.0-linux-arm64.tar.xz: Exec format error

### ISSUE THREAD

**Issue by markmartirosian** [tetratelabs/archive-envoy#43]
```sh
wget https://archive.tetratelabs.io/envoy/download/v1.23.0/envoy-v1.23.0-linux-arm64.tar.xz

[ec2-user@i-005c9473506c71729 bin]$ ./envoy
-bash: ./envoy: cannot execute binary file: Exec format error
```

**Comment by cpakulski** [comment]
@markmartirosian can you provide same details about the platform where you try to run Envoy binary?

I may be slow with responses as I am away for few weeks.

**Comment by markmartirosian** [comment]
AWS EC2 t4g instance running centos 9. The 1.22.0 is working.

**Comment by ahjohannessen** [comment]
I got the same issue with MacBook Pro M1 running a Linux VM.

**Comment by codefromthecrypt** [comment]
@markmartirosian these archives are built from the official docker image. can you check to see if envoyproxy/envoy:v1.23.0 works for you?

@ahjohannessen fyi v1.23.0 on Mac is blocking on https://github.com/Homebrew/homebrew-core/pull/105900

**Comment by markmartirosian** [comment]
@codefromthecrypt that's right, it seems to be a docker image issue.

```
[root@i-0fca45895a9b81442 ec2-user]# docker run -it envoyproxy/envoy:v1.23.0
Unable to find image 'envoyproxy/envoy:v1.23.0' locally
v1.23.0: Pulling from envoyproxy/envoy
8376114ff9b3: Pull complete
bc45fc51b638: Pull complete
ef89a4cf0efa: Pull complete
bd4430a287b9: Pull complete
3e54b87113ea: Pull complete
b6eec207dd6c: Pull complete
adb2b2bea0ee: Pull complete
49506b69cdb6: Pull complete
Digest: sha256:b8dde8b3f8adc0fb9fb581ed566399a67398f83588cf26d0604e1c9c9fd3b557
Status: Downloaded newer image for envoyproxy/envoy:v1.23.0
/docker-entrypoint.sh: 29: exec: su-exec: Exec format error
```

```
[root@i-0fca45895a9b81442 ec2-user]# docker run -it envoyproxy/envoy:v1.22.0
Unable to find image 'envoyproxy/envoy:v1.22.0' locally
v1.22.0: Pulling from envoyproxy/envoy
d35feac4abe8: Pull complete
f18e9d859af6: Pull complete
039c0eedb2e7: Pull complete
d472b5907dbd: Pull complete
3f7d6d6f4fcf: Pull complete
877b93bbcadd: Pull complete
835f55682df1: Pull complete
6aba25efd78c: Pull complete
Digest: sha256:478044b54936608dd3115c89ea9fe5be670f1e78d4436927c096b4bc06eeedeb
Status: Downloaded newer image for envoyproxy/envoy:v1.22.0
[2022-08-16 12:23:45.734][1][info][main] [source/server/server.cc:390] initializing epoch 0 (base id=0, hot restart version=11.120)
```

**Comment by codefromthecrypt** [comment]
sorry @ahjohannessen indeed I missed the end of your sentence. I doubt envoy will re-publish the broken 1.23.0 docker image, but can one of you raise an issue to make sure? https://github.com/envoyproxy/envoy/issues/new/choose

once the docker image is fixed (they might say wait until 1.23.1) then either way the archive can be redone

**Comment by codefromthecrypt** [comment]
ah I see @markmartirosian already opened an issue. this issue needs to await an outcome

* broken linux arm64 https://github.com/envoyproxy/envoy/issues/22721
* missing Darwin https://github.com/Homebrew/homebrew-core/pull/105900

**Comment by lizan** [comment]
The docker image will be fixed in v1.23.1.

If we want to repack the archive, use binary from [azure pipelines artifacts](https://dev.azure.com/cncf/envoy/_build/results?buildId=113045&view=artifacts&pathAsName=false&type=publishedArtifacts).

**Comment by codefromthecrypt** [comment]
@ahjohannessen @markmartirosian can you verify that 1.23.1 fixed the linux issue? ack os/x is still out of commission https://github.com/Homebrew/homebrew-core/pull/109023

**Comment by ahjohannessen** [comment]
@codefromthecrypt I can verify that 1.23.1 fixes the issue for me on my MacBook Pro M1 running a LINUX ARM VM.

```shell
[core@f01 ~]$ uname -oir && ./envoy --version
5.18.13-200.fc36.aarch64 aarch64 GNU/Linux

./envoy  version: edd69583372955fdfa0b8ca3820dd7312c094e46/1.23.1/Clean/RELEASE/BoringSSL
```

**Comment by codefromthecrypt** [comment]
ok I'll close this as the issue was about the linux archive. thanks for your patience folks

**Comment by markmartirosian** [comment]
AWS EC2 t4g instance running centos 9. The 1.22.0 is working.
